const products = [
  {
    id: 1001,
    subject: 'Maths',
    location: 'London',
    price: 459,
    space: 7,
    image: 'images/maths.jpg',
    cartquantity: 0,
  },
  {
    id: 1002,
    subject: 'English',
    location: 'London',
    price: 638,
    space: 6,
    image: 'images/English.jpg',
    cartquantity: 0,
  },
  {
    id: 1003,
    subject: 'Physics',
    location: 'London',
    price: 458,
    space: 5,
    image: 'images/physics.jpeg',
    cartquantity: 0,
  },
  {
    id: 1004,
    subject: 'Criminology',
    location: 'London',
    price: 105,
    space: 15,
    image: 'images/criminology.jpg',
    cartquantity: 0,
  },
  {
    id: 1005,
    subject: 'Law',
    location: 'London',
    price: 985,
    space: 19,
    image: 'images/law.jpeg',
    cartquantity: 0,
  },
  {
    id: 1006,
    subject: 'Maths',
    location: 'Dubai',
    price: 1025,
    space: 12,
    image: 'images/maths.jpg',
    cartquantity: 0,
  },
  {
    id: 1007,
    subject: 'English',
    location: 'Dubai',
    price: 195,
    space: 4,
    image: 'images/english.jpg',
    cartquantity: 0,
  },
  {
    id: 1008,
    subject: 'Physics',
    location: 'Dubai',
    price: 450,
    space: 6,
    image: 'images/physics.jpeg',
    cartquantity: 0,
  },
  {
    id: 1009,
    subject: 'Criminology',
    location: 'Dubai',
    price: 650,
    space: 7,
    image: 'images/criminology.jpg',
    cartquantity: 0,
  },
  {
    id: 1010,
    subject: 'Law',
    location: 'Dubai',
    price: 800,
    space: 25,
    image: 'images/law.jpeg',
    cartquantity: 0,
  },

];